import { jsPDF } from "jspdf"
import { categoryName } from "./categories"
import { formatCoords, formatDateTime, shortHash } from "./format"
import type { Incident } from "./types"

interface InvestigatorProfile {
  name?: string
  governmentId?: string
  organization?: string
  phone?: string
  email?: string
}

function hasProfileContent(profile: InvestigatorProfile | null): boolean {
  if (!profile) return false
  return Boolean(
    profile.name?.trim() ||
      profile.governmentId?.trim() ||
      profile.organization?.trim() ||
      profile.phone?.trim() ||
      profile.email?.trim(),
  )
}

/**
 * Generates a single-incident PDF report: investigator identity header
 * (only if filled out), incident details, GPS, evidence file list with
 * hashes, and seal info if sealed. Returns the PDF as a Blob for saving
 * or sharing — does not write to disk itself.
 */
export function generateIncidentPdf(
  incident: Incident,
  profile: InvestigatorProfile | null,
): Blob {
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 48
  let y = margin

  function line(height = 16) {
    y += height
  }

  function checkPageBreak(needed = 40) {
    if (y > doc.internal.pageSize.getHeight() - needed) {
      doc.addPage()
      y = margin
    }
  }

  function heading(text: string, size = 13) {
    checkPageBreak()
    doc.setFont("helvetica", "bold")
    doc.setFontSize(size)
    doc.text(text, margin, y)
    line(size + 6)
    doc.setFont("helvetica", "normal")
  }

  function body(text: string, size = 10) {
    doc.setFontSize(size)
    const wrapped = doc.splitTextToSize(text, pageWidth - margin * 2)
    for (const wline of wrapped) {
      checkPageBreak()
      doc.text(wline, margin, y)
      line(size + 4)
    }
  }

  function labelValue(label: string, value: string) {
    checkPageBreak()
    doc.setFont("helvetica", "bold")
    doc.setFontSize(9)
    doc.text(label, margin, y)
    doc.setFont("helvetica", "normal")
    doc.text(value, margin + 110, y)
    line(15)
  }

  // --- Investigator identity header (only if any field is filled) ---
  if (hasProfileContent(profile)) {
    heading("Investigator Identity", 11)
    if (profile?.name?.trim()) labelValue("Name:", profile.name.trim())
    if (profile?.governmentId?.trim())
      labelValue("Government ID:", profile.governmentId.trim())
    if (profile?.organization?.trim())
      labelValue("Organization:", profile.organization.trim())
    if (profile?.phone?.trim()) labelValue("Phone:", profile.phone.trim())
    if (profile?.email?.trim()) labelValue("Email:", profile.email.trim())
    line(10)
    doc.setDrawColor(200)
    doc.line(margin, y, pageWidth - margin, y)
    line(20)
  }

  // --- Incident header ---
  heading(incident.title || "Untitled incident", 16)

  labelValue("Category:", categoryName(incident.category))
  labelValue("Occurred:", formatDateTime(incident.occurredAt))
  labelValue("Logged:", formatDateTime(incident.createdAt))
  labelValue("Status:", incident.sealed ? "Sealed" : "Unsealed")
  if (incident.location) {
    labelValue(
      "GPS:",
      formatCoords(incident.location.latitude, incident.location.longitude),
    )
  }
  line(10)

  // --- Description ---
  heading("Description", 12)
  body(incident.description?.trim() || "No description provided.")
  line(10)

  // --- Evidence list ---
  heading(`Evidence (${incident.evidence.length})`, 12)
  if (incident.evidence.length === 0) {
    body("No attachments on this record.")
  } else {
    for (const ev of incident.evidence) {
      checkPageBreak(30)
      doc.setFont("helvetica", "bold")
      doc.setFontSize(9.5)
      doc.text(`• ${ev.kind}`, margin, y)
      line(13)
      doc.setFont("helvetica", "normal")
      doc.setFontSize(8.5)
      doc.setTextColor(90)
      doc.text(
        `SHA-256: ${shortHash(ev.sha256, 16)}  ·  ${ev.mimeType}  ·  ${new Date(ev.createdAt).toLocaleString()}`,
        margin + 12,
        y,
      )
      doc.setTextColor(0)
      line(16)
    }
  }
  line(10)

  // --- Seal info ---
  if (incident.sealed && incident.seal) {
    heading("Evidence Seal", 12)
    labelValue("Sealed at:", formatDateTime(incident.seal.sealedAt))
    body(`SHA-256 (canonical hash): ${incident.seal.hash}`, 8.5)
  }

  // --- Footer with generation timestamp ---
  const pageCount = doc.internal.pages.length - 1
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setFontSize(7.5)
    doc.setTextColor(150)
    doc.text(
      `Generated by Witness Protocol · ${new Date().toLocaleString()} · Page ${p} of ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 20,
    )
    doc.setTextColor(0)
  }

  return doc.output("blob")
}
